### ISSUE TITLE
Inherit Service Notifications contacts from hosts contacts not working after upgrade.

### ISSUE THREAD

**Issue by postmannen** [centreon/centreon-engine#19]
Hi.

I've earlier used Centreon 2.5.4 with Nagios 3.0. There I had all the configuration for who should get notification in the host templates. I had no notification config for people in the service's, since the services inherited the contacts from the host templates.

Now I've setup a new server with Centreon 2.6.1 and replaced nagios with Centengine 1.4.11. With the new setup and same host and services configuration I get notifications when a host goes down, but when a service goes not-ok I don't get notified. 

If I put in a contact for notification directly in the service defenition I get notification when a service goes down. So it seems the problem is that its no longer able to inherit the hosts contacts for use with for service alerts.

When I check the centengine.log I can see the service alert in the log, but no notification is created unless I configure a contact directly in the service.

I've allso tried with Centengine 1.4.13, but same problem.

Kind regards
Bjorn Tore.

**Comment by postmannen** [comment]
Hi again.

Just want to add some info.

Checked here on Github and there are 2 similar issues there.

One posted under Centreon. https://github.com/centreon/centreon/issues/881
Another posted under Centreon https://github.com/centreon/centreon/issues/1591

And mine posted under Centreon-Engine https://github.com/centreon/centreon-engine/issues/19 since I believe this is related to centreon-engine since thats the service who controls the logic on the satellites.

The one posted under Centreon is commented with milestone 2.6.3. But is this actually a problem in Centreon, and not in Centreon Engine ?

I've tried setting up a new Satellite today with Ubuntu as Os (Debian earlier), and now with Centreon-engine 1.4.14. But it seems the problem are there same.

I've allso tested editing the record for a test service i made in mysql and set service_inherit_contacts_from_host from "null" to "1", but that does not make any difference. It still not inherit the contacts from the host if none are specified in the service.

Regards
Bjorn Tore.

**Comment by ganoze** [comment]
Issue is confirmed, host contacts are not inherited (on purpose) in services, as per the documentation.

However it seems that implicit host contact inheritance is the original behavior from Nagios (despite what its documentation suggests) so we will implement it and update our documentation accordingly.

**Comment by ganoze** [comment]
BTW, thank you for pointing out other open issues :-)

**Comment by postmannen** [comment]
Thank you Ganoze :)

**Comment by lunze** [comment]
Hi, i have a problem with inheritance of contacts and groups.
This topic matches best, thats why i will post it here.

I am using the following software-versions:
centreon-engine 1.4.13
centreon 2.6.1
centreon-broker 2.8.2

So first, i create a host which is using a hosttemplate.
There are a few servicetemplates which are connected to this hosttemplate.
Than i connect a contactgroup to this host.

After creation all contacts will be notified if a problem occurs with the host or some services of its hosttemplate.
Thats all fine, because the services inherit from the host, they are connected to.

Now i want additionally inform another group if there is a problem with any instance of one special servicetemplate.
Thats why i connect this group to this special servicetemplates.

The problem is, that only this group is informed and not anymore the group which is connected to the host.
Is it possible to create a new function to "Inherit contacts from host" which will ever work? Not only for services, also for servicetemplates!

I know there is such a function for services, but this only works if the service has no contacts defined.
Such a new function would be very helpful, because now i have to add all contactgroups of the host to the services manually after creation out of templates.

If you need more informations from me let me know it.
With nice regards.

PS: or is there a possibility / way to create such a behaviour?

**Comment by postmannen** [comment]
Thanks for the help implementing this :)

Kind regards
 Bjørn Tore.
