### ISSUE TITLE
Exclusion of TimePeriod doesn't work

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon-engine#32]
Hello,

I try do apply this configuration:
define timeperiod{
        name                            Exclusion
        timeperiod_name                 Exclusion
        alias                           Exclusion
        november 5                      10:00-13:00
}
define timeperiod{
        name                            Enterprise
        timeperiod_name                 Enterprise
        alias                           Enterprise
        sunday                          08:00-20:00,20:20-24:00
        monday                          08:00-20:00,20:20-24:00
        tuesday                         08:00-20:00,20:20-24:00
        wednesday                               08:00-20:00,20:20-24:00
        thursday                                08:00-20:00,20:20-24:00
        friday                          08:00-20:00,20:20-24:00
        saturday                                08:00-20:00,20:20-24:00
        exclude                         Exception
}

The problem is my service (with the check timeperiod "Enterprise") is checked the 5 november between 10:00 and 13:00.

Regards

**Comment by ganoze** [comment]
In Centreon Engine 1.x, the timeperiod code is known to be buggy. Especially exclusions are known to not work (our 30 exclusion unit tests indicate so). This is why the whole timeperiod code was rewritten in Centreon Engine 2.x. We cannot backport this change because of incompatible data structures and as a consequence this bug won't be fixed.
