### ISSUE TITLE
contacts.cfg doesn't have all my users ?

### ISSUE THREAD

**Issue by Eldertoon** [centreon/centreon-engine#83]
Hi,

I am investigating why I can't send notification to some of my users and I see contacts.cfg doesn't list all user that are in the centreon web UI. For what I see, only users in Supervisors are created and contactgroups.cfg only list Supervisors.

When I log as root, everything works as expected in web. When i use a simple user, it works like in centreon-engine (only one group and only users of this group listed).

I suppose something is broken, maybe with the database, with ACL ?, but I don't find anything.

Regards,

**Comment by Eldertoon** [comment]
I forgot : using Centreon 2.8.9 on CentOS 6.9 if I'm correct

**Comment by ganoze** [comment]
Hello and thank you for your report.

If your contacts.cfg file only contains a subset of the expected content, I suggest that you open a ticket on the Centreon Web project (https://github.com/centreon/centreon) with a detailed scenario because it is this project that Centreon Engine configuration files are generated.
